### ISSUE TITLE
Can't bypass ASPX pages

### ISSUE THREAD

**Issue by AndyMcKenna** [davidfowl/IISCrossover#2]
I'm attempting to have a URL that is an ASPX page fall through to the DotNetCore app without success.  It works for extensionless URLs and my commit works for that particular page but now all the other ASPX pages that should still be handled by Legacy fail.  I think I'm doing something wrong with my subclass of `PageHandlerFactory`

https://github.com/AndyMcKenna/IISCrossover/commit/a801b669b2e4162e6d625b86b44a3e96a360ed39

**Comment by davidfowl** [comment]
I'm playing with this scenario; will let you know when I have something. So far, IIS is defeating me...

**Comment by davidfowl** [comment]
Here's my first stab at this https://github.com/davidfowl/IISCrossover/commit/47580fb0eac56f524e556645438382103e79f5a2. It forces all pages to go through routing so that they follow the same pattern. It seems the PageHandlerFactory runs super late. The other thing that can be done with routing is using patterns. So you can map {*page}.aspx and then selectively move pages to ASP.NET Core.

In fact, I'll try that!

**Comment by davidfowl** [comment]
OK [this commit](https://github.com/davidfowl/IISCrossover/commit/edcfc59a1c8abfe44ae6241fded5aa539dcee2d8) handles all .aspx pages via routing automagically and lets you follow the same technique to forward to the ASP.NET Core application.

**Comment by davidfowl** [comment]
Closing this as solved!
